/*
 * Created by SharpDevelop.
 * User: Bob Swift
 * Date: 2016-10-10
 * Time: 11:27
 * 
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */
using System;
using System.Collections.Generic;

namespace HHBuilder
{
	
	/// <summary>
	/// Class for handling standard language settings
	/// </summary>
	public class Language
	{
		/// <summary>
		/// Title and location (if applicable) of the language
		/// </summary>
		public string Title { get; set; }
		
		/// <summary>
		/// Hexidecimal code for the language in the form 0x0000
		/// </summary>
		public string Code { get; set; }
		
		/// <summary>
		/// Language code and title
		/// </summary>
		/// <returns>Code and title in the form "0x0000 Language (optional location)"</returns>
		public string CodeText() { return string.Format("{0} {1}", Code, Title); }
		
		/// <summary>
		/// Language titles and codes
		/// </summary>
		/// <returns>Complete list of Language class elements</returns>
		public static List<Language> GetList()
		{
			return new List<Language>
			{
				new Language() { Title = "Afrikaans (South Africa)", Code = "0x0436" },
				new Language() { Title = "Albanian (Albania)", Code = "0x041C" },
				new Language() { Title = "Alsatian", Code = "0x0484" },
				new Language() { Title = "Amharic (Ethiopia)", Code = "0x045E" },
				new Language() { Title = "Arabic (Saudi Arabia)", Code = "0x0401" },
				new Language() { Title = "Arabic (Algeria)", Code = "0x1401" },
				new Language() { Title = "Arabic (Bahrain)", Code = "0x3C01" },
				new Language() { Title = "Arabic (Egypt)", Code = "0x0C01" },
				new Language() { Title = "Arabic (Iraq)", Code = "0x0801" },
				new Language() { Title = "Arabic (Jordan)", Code = "0x2C01" },
				new Language() { Title = "Arabic (Kuwait)", Code = "0x3401" },
				new Language() { Title = "Arabic (Lebanon)", Code = "0x3001" },
				new Language() { Title = "Arabic (Libya)", Code = "0x1001" },
				new Language() { Title = "Arabic (Morocco)", Code = "0x1801" },
				new Language() { Title = "Arabic (Oman)", Code = "0x2001" },
				new Language() { Title = "Arabic (Qatar)", Code = "0x4001" },
				new Language() { Title = "Arabic (Syria)", Code = "0x2801" },
				new Language() { Title = "Arabic (Tunisia)", Code = "0x1C01" },
				new Language() { Title = "Arabic (U.A.E.)", Code = "0x3801" },
				new Language() { Title = "Arabic (Yemen)", Code = "0x2401" },
				new Language() { Title = "Armenian (Armenia)", Code = "0x042B" },
				new Language() { Title = "Assamese", Code = "0x044D" },
				new Language() { Title = "Azeri (Cyrillic)", Code = "0x082C" },
				new Language() { Title = "Azeri (Latin)", Code = "0x042C" },
				new Language() { Title = "Bashkir", Code = "0x046D" },
				new Language() { Title = "Basque", Code = "0x042D" },
				new Language() { Title = "Belarusian", Code = "0x0423" },
				new Language() { Title = "Bengali (India)", Code = "0x0445" },
				new Language() { Title = "Bengali (Bangladesh)", Code = "0x0845" },
				new Language() { Title = "Bosnian (Bosnia/Herzegovina)", Code = "0x141A" },
				new Language() { Title = "Breton", Code = "0x047E" },
				new Language() { Title = "Bulgarian", Code = "0x0402" },
				new Language() { Title = "Burmese", Code = "0x0455" },
				new Language() { Title = "Catalan", Code = "0x0403" },
				new Language() { Title = "Cherokee (United States)", Code = "0x045C" },
				new Language() { Title = "Chinese (People's Republic of China)", Code = "0x0804" },
				new Language() { Title = "Chinese (Singapore)", Code = "0x1004" },
				new Language() { Title = "Chinese (Taiwan)", Code = "0x0404" },
				new Language() { Title = "Chinese (Hong Kong SAR)", Code = "0x0C04" },
				new Language() { Title = "Chinese (Macao SAR)", Code = "0x1404" },
				new Language() { Title = "Corsican", Code = "0x0483" },
				new Language() { Title = "Croatian", Code = "0x041A" },
				new Language() { Title = "Croatian (Bosnia/Herzegovina)", Code = "0x101A" },
				new Language() { Title = "Czech", Code = "0x0405" },
				new Language() { Title = "Danish", Code = "0x0406" },
				new Language() { Title = "Dari", Code = "0x048C" },
				new Language() { Title = "Divehi", Code = "0x0465" },
				new Language() { Title = "Dutch (Netherlands)", Code = "0x0413" },
				new Language() { Title = "Dutch (Belgium)", Code = "0x0813" },
				new Language() { Title = "Edo", Code = "0x0466" },
				new Language() { Title = "English (United States)", Code = "0x0409" },
				new Language() { Title = "English (United Kingdom)", Code = "0x0809" },
				new Language() { Title = "English (Australia)", Code = "0x0C09" },
				new Language() { Title = "English (Belize)", Code = "0x2809" },
				new Language() { Title = "English (Canada)", Code = "0x1009" },
				new Language() { Title = "English (Caribbean)", Code = "0x2409" },
				new Language() { Title = "English (Hong Kong SAR)", Code = "0x3C09" },
				new Language() { Title = "English (India)", Code = "0x4009" },
				new Language() { Title = "English (Indonesia)", Code = "0x3809" },
				new Language() { Title = "English (Ireland)", Code = "0x1809" },
				new Language() { Title = "English (Jamaica)", Code = "0x2009" },
				new Language() { Title = "English (Malaysia)", Code = "0x4409" },
				new Language() { Title = "English (New Zealand)", Code = "0x1409" },
				new Language() { Title = "English (Philippines)", Code = "0x3409" },
				new Language() { Title = "English (Singapore)", Code = "0x4809" },
				new Language() { Title = "English (South Africa)", Code = "0x1C09" },
				new Language() { Title = "English (Trinidad)", Code = "0x2C09" },
				new Language() { Title = "English (Zimbabwe)", Code = "0x3009" },
				new Language() { Title = "Estonian", Code = "0x0425" },
				new Language() { Title = "Faroese", Code = "0x0438" },
				new Language() { Title = "Farsi", Code = "0x0429" },
				new Language() { Title = "Filipino", Code = "0x0464" },
				new Language() { Title = "Finnish", Code = "0x040B" },
				new Language() { Title = "French (France)", Code = "0x040C" },
				new Language() { Title = "French (Belgium)", Code = "0x080C" },
				new Language() { Title = "French (Cameroon)", Code = "0x2C0C" },
				new Language() { Title = "French (Canada)", Code = "0x0C0C" },
				new Language() { Title = "French (Democratic Rep. of Congo)", Code = "0x240C" },
				new Language() { Title = "French (Cote d'Ivoire)", Code = "0x300C" },
				new Language() { Title = "French (Haiti)", Code = "0x3C0C" },
				new Language() { Title = "French (Luxembourg)", Code = "0x140C" },
				new Language() { Title = "French (Mali)", Code = "0x340C" },
				new Language() { Title = "French (Monaco)", Code = "0x180C" },
				new Language() { Title = "French (Morocco)", Code = "0x380C" },
				new Language() { Title = "French (North Africa)", Code = "0xE40C" },
				new Language() { Title = "French (Reunion)", Code = "0x200C" },
				new Language() { Title = "French (Senegal)", Code = "0x280C" },
				new Language() { Title = "French (Switzerland)", Code = "0x100C" },
				new Language() { Title = "French (West Indies)", Code = "0x1C0C" },
				new Language() { Title = "Frisian (Netherlands)", Code = "0x0462" },
				new Language() { Title = "Fulfulde (Nigeria)", Code = "0x0467" },
				new Language() { Title = "FYRO Macedonian", Code = "0x042F" },
				new Language() { Title = "Galician", Code = "0x0456" },
				new Language() { Title = "Georgian", Code = "0x0437" },
				new Language() { Title = "German (Germany)", Code = "0x0407" },
				new Language() { Title = "German (Austria)", Code = "0x0C07" },
				new Language() { Title = "German (Liechtenstein)", Code = "0x1407" },
				new Language() { Title = "German (Luxembourg)", Code = "0x1007" },
				new Language() { Title = "German (Switzerland)", Code = "0x0807" },
				new Language() { Title = "Greek", Code = "0x0408" },
				new Language() { Title = "Greenlandic", Code = "0x046F" },
				new Language() { Title = "Guarani (Paraguay)", Code = "0x0474" },
				new Language() { Title = "Gujarati", Code = "0x0447" },
				new Language() { Title = "Hausa (Nigeria)", Code = "0x0468" },
				new Language() { Title = "Hawaiian (United States)", Code = "0x0475" },
				new Language() { Title = "Hebrew", Code = "0x040D" },
				new Language() { Title = "Hindi", Code = "0x0439" },
				new Language() { Title = "Hungarian", Code = "0x040E" },
				new Language() { Title = "Ibibio (Nigeria)", Code = "0x0469" },
				new Language() { Title = "Icelandic", Code = "0x040F" },
				new Language() { Title = "Igbo (Nigeria)", Code = "0x0470" },
				new Language() { Title = "Indonesian", Code = "0x0421" },
				new Language() { Title = "Inuktitut", Code = "0x045D" },
				new Language() { Title = "Irish", Code = "0x083C" },
				new Language() { Title = "Italian (Italy)", Code = "0x0410" },
				new Language() { Title = "Italian (Switzerland)", Code = "0x0810" },
				new Language() { Title = "Japanese", Code = "0x0411" },
				new Language() { Title = "K'iche", Code = "0x0486" },
				new Language() { Title = "Kannada", Code = "0x044B" },
				new Language() { Title = "Kanuri (Nigeria)", Code = "0x0471" },
				new Language() { Title = "Kashmiri", Code = "0x0860" },
				new Language() { Title = "Kashmiri (Arabic)", Code = "0x0460" },
				new Language() { Title = "Kazakh", Code = "0x043F" },
				new Language() { Title = "Khmer", Code = "0x0453" },
				new Language() { Title = "Kinyarwanda", Code = "0x0487" },
				new Language() { Title = "Konkani", Code = "0x0457" },
				new Language() { Title = "Korean", Code = "0x0412" },
				new Language() { Title = "Kyrgyz (Cyrillic)", Code = "0x0440" },
				new Language() { Title = "Lao", Code = "0x0454" },
				new Language() { Title = "Latin", Code = "0x0476" },
				new Language() { Title = "Latvian", Code = "0x0426" },
				new Language() { Title = "Lithuanian", Code = "0x0427" },
				new Language() { Title = "Luxembourgish", Code = "0x046E" },
				new Language() { Title = "Malay (Malaysia)", Code = "0x043E" },
				new Language() { Title = "Malay (Brunei Darussalam)", Code = "0x083E" },
				new Language() { Title = "Malayalam", Code = "0x044C" },
				new Language() { Title = "Maltese", Code = "0x043A" },
				new Language() { Title = "Manipuri", Code = "0x0458" },
				new Language() { Title = "Maori (New Zealand)", Code = "0x0481" },
				new Language() { Title = "Mapudungun", Code = "0x047A" },
				new Language() { Title = "Marathi", Code = "0x044E" },
				new Language() { Title = "Mohawk", Code = "0x047C" },
				new Language() { Title = "Mongolian (Cyrillic)", Code = "0x0450" },
				new Language() { Title = "Mongolian (Mongolian)", Code = "0x0850" },
				new Language() { Title = "Nepali", Code = "0x0461" },
				new Language() { Title = "Nepali (India)", Code = "0x0861" },
				new Language() { Title = "Norwegian (BokmÃ¥l)", Code = "0x0414" },
				new Language() { Title = "Norwegian (Nynorsk)", Code = "0x0814" },
				new Language() { Title = "Occitan", Code = "0x0482" },
				new Language() { Title = "Oriya", Code = "0x0448" },
				new Language() { Title = "Oromo", Code = "0x0472" },
				new Language() { Title = "Papiamentu", Code = "0x0479" },
				new Language() { Title = "Pashto", Code = "0x0463" },
				new Language() { Title = "Polish", Code = "0x0415" },
				new Language() { Title = "Portuguese (Brazil)", Code = "0x0416" },
				new Language() { Title = "Portuguese (Portugal)", Code = "0x0816" },
				new Language() { Title = "Punjabi", Code = "0x0446" },
				new Language() { Title = "Punjabi (Pakistan)", Code = "0x0846" },
				new Language() { Title = "Quecha (Bolivia)", Code = "0x046B" },
				new Language() { Title = "Quecha (Ecuador)", Code = "0x086B" },
				new Language() { Title = "Quecha (Peru)", Code = "0x0C6B" },
				new Language() { Title = "Rhaeto-Romanic", Code = "0x0417" },
				new Language() { Title = "Romanian", Code = "0x0418" },
				new Language() { Title = "Romanian (Moldava)", Code = "0x0818" },
				new Language() { Title = "Russian", Code = "0x0419" },
				new Language() { Title = "Russian (Moldava)", Code = "0x0819" },
				new Language() { Title = "Sami (Lappish)", Code = "0x043B" },
				new Language() { Title = "Sanskrit", Code = "0x044F" },
				new Language() { Title = "Scottish Gaelic", Code = "0x043C" },
				new Language() { Title = "Sepedi", Code = "0x046C" },
				new Language() { Title = "Serbian (Cyrillic)", Code = "0x0C1A" },
				new Language() { Title = "Serbian (Latin)", Code = "0x081A" },
				new Language() { Title = "Sindhi (India)", Code = "0x0459" },
				new Language() { Title = "Sindhi (Pakistan)", Code = "0x0859" },
				new Language() { Title = "Sinhalese (Sri Lanka)", Code = "0x045B" },
				new Language() { Title = "Slovak", Code = "0x041B" },
				new Language() { Title = "Slovenian", Code = "0x0424" },
				new Language() { Title = "Somali", Code = "0x0477" },
				new Language() { Title = "Sorbian", Code = "0x042E" },
				new Language() { Title = "Spanish (Spain (Modern Sort)", Code = "0x0C0A" },
				new Language() { Title = "Spanish (Spain (Traditional Sort)", Code = "0x040A" },
				new Language() { Title = "Spanish (Argentina)", Code = "0x2C0A" },
				new Language() { Title = "Spanish (Bolivia)", Code = "0x400A" },
				new Language() { Title = "Spanish (Chile)", Code = "0x340A" },
				new Language() { Title = "Spanish (Colombia)", Code = "0x240A" },
				new Language() { Title = "Spanish (Costa Rica)", Code = "0x140A" },
				new Language() { Title = "Spanish (Dominican Republic)", Code = "0x1C0A" },
				new Language() { Title = "Spanish (Ecuador)", Code = "0x300A" },
				new Language() { Title = "Spanish (El Salvador)", Code = "0x440A" },
				new Language() { Title = "Spanish (Guatemala)", Code = "0x100A" },
				new Language() { Title = "Spanish (Honduras)", Code = "0x480A" },
				new Language() { Title = "Spanish (Latin America)", Code = "0x580A" },
				new Language() { Title = "Spanish (Mexico)", Code = "0x080A" },
				new Language() { Title = "Spanish (Nicaragua)", Code = "0x4C0A" },
				new Language() { Title = "Spanish (Panama)", Code = "0x180A" },
				new Language() { Title = "Spanish (Paraguay)", Code = "0x3C0A" },
				new Language() { Title = "Spanish (Peru)", Code = "0x280A" },
				new Language() { Title = "Spanish (Puerto Rico)", Code = "0x500A" },
				new Language() { Title = "Spanish (United States)", Code = "0x540A" },
				new Language() { Title = "Spanish (Uruguay)", Code = "0x380A" },
				new Language() { Title = "Spanish (Venezuela)", Code = "0x200A" },
				new Language() { Title = "Sutu", Code = "0x0430" },
				new Language() { Title = "Swahili", Code = "0x0441" },
				new Language() { Title = "Swedish", Code = "0x041D" },
				new Language() { Title = "Swedish (Finland)", Code = "0x081D" },
				new Language() { Title = "Syriac", Code = "0x045A" },
				new Language() { Title = "Tajik", Code = "0x0428" },
				new Language() { Title = "Tamazight (Arabic)", Code = "0x045F" },
				new Language() { Title = "Tamazight (Latin)", Code = "0x085F" },
				new Language() { Title = "Tamil", Code = "0x0449" },
				new Language() { Title = "Tatar", Code = "0x0444" },
				new Language() { Title = "Telugu", Code = "0x044A" },
				new Language() { Title = "Thai", Code = "0x041E" },
				new Language() { Title = "Tibetan (Bhutan)", Code = "0x0851" },
				new Language() { Title = "Tibetan (People's Republic of China)", Code = "0x0451" },
				new Language() { Title = "Tigrigna (Eritrea)", Code = "0x0873" },
				new Language() { Title = "Tigrigna (Ethiopia)", Code = "0x0473" },
				new Language() { Title = "Tsonga", Code = "0x0431" },
				new Language() { Title = "Tswana", Code = "0x0432" },
				new Language() { Title = "Turkish", Code = "0x041F" },
				new Language() { Title = "Turkmen", Code = "0x0442" },
				new Language() { Title = "Uighur (China)", Code = "0x0480" },
				new Language() { Title = "Ukrainian", Code = "0x0422" },
				new Language() { Title = "Urdu", Code = "0x0420" },
				new Language() { Title = "Urdu (India)", Code = "0x0820" },
				new Language() { Title = "Uzbek (Cyrillic)", Code = "0x0843" },
				new Language() { Title = "Uzbek (Latin)", Code = "0x0443" },
				new Language() { Title = "Venda", Code = "0x0433" },
				new Language() { Title = "Vietnamese", Code = "0x042A" },
				new Language() { Title = "Welsh", Code = "0x0452" },
				new Language() { Title = "Wolof", Code = "0x0488" },
				new Language() { Title = "Xhosa", Code = "0x0434" },
				new Language() { Title = "Yakut", Code = "0x0485" },
				new Language() { Title = "Yi", Code = "0x0478" },
				new Language() { Title = "Yiddish", Code = "0x043D" },
				new Language() { Title = "Yoruba", Code = "0x046A" },
				new Language() { Title = "Zulu", Code = "0x0435" }
			};
		}
	}
}
